# need to input landmarks

landmark_choices = {
  'a': 'Boston Common',
  'b': 'Boston Childrens Museum',
  'c': 'Capen Building: Union Oyster House',
  'd': 'Carson Beach',
  'e': 'Castle Island',
  'f': 'City Hall',
  'g': 'Community Boating',
  'h': 'Danehy Park',
  'i': 'Donald McKay Memorial',
  'j': 'Edward M. Kennedy Institute for the United State Senate',
  'k': 'Esplanade',
  'l': 'Freedom Trail',
  'm': 'French Common',
  'n': 'Harbor Walk',
  'o': 'Harvard Museum',
  'p': 'Holocaust Memorial',
  'q': 'John F. Kennedy Presidential Library and Museum',
  'r': 'Lexington Park; Community Garden',
  's': 'Minuteman Bikeway',
  't': 'MIT Museum',
  'u': 'Mr. Bartleys Burgers',
  'v': 'Public Garden',
  'w': 'Quincy Market',
  'x': 'Retail and Shopping',
  'y': 'Somerville Open Studions',
  'z': 'Sunset Lake',
  'zz': 'Tea Party Museum'
}